name: polylogyx-esp-kubernetes
description: A Helm Chart for deploying the polylogyx endpoint security platform
version: 0.0.2
apiVersion: v2
appVersion: 2.1.2
sources:
home: https://github.com/arava-kishore/er-ce
keywords:
  - osquery
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    version: 14.3.0
    repository: https://charts.bitnami.com/bitnami
  - condition: rabbitmq.enabled
    name: rabbitmq
    version: 8.5.4
    repository: https://charts.bitnami.com/bitnami
  - condition: redis.enabled
    name: redis
    version: 7.0
    repository: https://charts.bitnami.com/bitnami
