# Stage 1
FROM node:14-alpine as build-step
RUN mkdir -p /app
WORKDIR /app
RUN mkdir -p plgx-angular-ui
COPY ./plgx-angular-ui/. /app/plgx-angular-ui/
RUN cd plgx-angular-ui && npm install
RUN cd plgx-angular-ui && npm install -g @angular/cli@13.2.3
RUN cd plgx-angular-ui && npm i gzipper@3.7.0 -g
RUN cd plgx-angular-ui && ng build --prod --stats-json && gzipper --verbose ../dist

# Stage 2
FROM nginx:1.17.1-alpine
RUN mkdir -p /app
WORKDIR /app
COPY --from=build-step /app/dist /app
COPY --from=build-step /app/resources /app/downloads
COPY --from=build-step /app/nginx /etc/nginx
EXPOSE 80

