{{ if .Values.plgx.rsyslogf.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polylogyx.fullname" . }}-rsyslogf-cfg
  labels: {{- include "polylogyx.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "polylogyx.fullname" . }}-rsyslogf
data:
  rsyslogd.conf: |
    module(load="imtcp")
    input(type="imtcp" port="514")
{{ end }}